<a href="https://colab.research.google.com/github/Bilalkhan-cel/Deep-Learning-Course/blob/main/Pytorch_F_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import torch
import torch as pt
torch.__version__

'2.11.0+cpu'

In [7]:
# intro to tensor
# ther are scaler vector and matrix tensors bacically 1d 2d and 3d tensors

scaler=torch.tensor(2)
print(scaler)
print(scaler.item()) # give us the no. in the tensor in form of int
print(scaler.ndim) # gives us the dimensions
print(scaler.itemsize) # returns the bytes


tensor(2)
2
0
8


In [8]:
# vetors
vector=torch.tensor([2,3])

# matrix
matrix=torch.tensor([[1,2,3],
                    [4,5,6]])

print(vector.shape)
print(matrix.shape)

torch.Size([2])
torch.Size([2, 3])


In [15]:
# Tensor
# Tensor a big martrix in which we can add mutiple matrix

TENSOR=torch.tensor([[[1,2,3],[4,5,6]], # matrix one of 2x3
                     [[2,2,2],[2,2,2]]]) # martix 2 of 2x3
print(TENSOR.shape)
print(TENSOR.ndim)
TENSOR[1]

torch.Size([2, 2, 3])
3


tensor([[2, 2, 2],
        [2, 2, 2]])

In [19]:
t=pt.tensor([[[1,2,3],[1,2,3],[1,2,4]]
             ,[[1,2,3],[1,2,4],[1,2,3]]])
print(t.shape)
print(t.ndim)
t[0]

torch.Size([2, 3, 3])
3


tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 4]])

In [23]:
## Random Tensors
# using radom no. in the tensors
# t=torch.rand(3,3) # is is just 3x3 matrix

t=torch.rand(2,3,3) # it will the create 2 3x3 matrix and ndim will be 3
t


tensor([[[0.2760, 0.5898, 0.0675],
         [0.4328, 0.5988, 0.8356],
         [0.9411, 0.2695, 0.2923]],

        [[0.5050, 0.0762, 0.6607],
         [0.3842, 0.1163, 0.6554],
         [0.7029, 0.9198, 0.6892]]])

In [24]:
# example Represent an image in a tensor
# it will be a tensor of (height,width,colour chanel(R,G,B))
img_tensor=pt.rand(224,224,3)
img_tensor.ndim , img_tensor.shape

(3, torch.Size([224, 224, 3]))

In [32]:
# Zeros Tensors
zero=pt.zeros(2,3,3)
ones=pt.ones(2,3,3)
ones


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [38]:
num=pt.arange(start=0,end=1100,step=100)

zero=pt.zeros_like(input=num)
zero


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
# we can aslo change the dtype of the tensors visitt documentation for more dtyeps